name: flutter_is_dark_color_hsp
description: This simple package use HSP color model to determine if a color is light or dark tone
version: 0.0.1
author: Aarón Montes
homepage: https://github.com/ajomuch92/flutter-is-dark-color-hsp

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
